---
dependencies:
  build_runner: ^2.4.6
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  freezed_annotation: ^2.4.1
  local_auth: ^2.1.6
  riverpod: ^2.3.6
description: A new Flutter project.
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=3.0.0 <4.0.0'
flutter:
  uses-material-design: true
name: biometric
publish_to: none
version: 1.0.0+1